#!/usr/bin/env bash
set -euo pipefail

## Set NEEDS_RESTARTING to one of "reboot" or "service" to switch on mocked output
NEEDS_RESTARTING=${NEEDS_RESTARTING:-none}

## Mock output for "needs-restarting" with no args
PLAIN=$(
  cat << 'EOF'
2697 : /usr/sbin/sshd -D
EOF
)

## Mock output for "needs-restarting --reboothint" or the shorthand "-r"
REBOOT_HINT=$(
  cat << 'EOF'
Core libraries or services have been updated:
  systemd -> 219-78.amzn2.0.20

Reboot is required to ensure that your system benefits from these updates.

More information:
https://access.redhat.com/solutions/27943
EOF
)

## Mock output for "needs-restarting --services" or the shorthand "-s"
NEEDS_RESTARTING_SERVICES=(${NEEDS_RESTARTING_SERVICES:-""})
printf -v SERVICE_RESTARTS "%s\n" "${NEEDS_RESTARTING_SERVICES[@]}"

if [[ "${NEEDS_RESTARTING}" == "reboot" ]]; then
  if [[ $# -eq 1 ]] && [[ $1 == "-r" || $1 == "--reboothint" ]]; then
    echo "${REBOOT_HINT}"
    exit 1
  fi
  echo "${PLAIN}"
  exit 0
elif [[ "${NEEDS_RESTARTING}" == "service" ]]; then
  echo "${SERVICE_RESTARTS}"
  exit 0
fi
